AWSTemplateFormatVersion: 2010-09-09

Parameters: 
  Environment:
    Description: Environment this stuck runs at
    Type: String
    Default: Dev
    AllowedValues:
      - Dev
      - Prod

Resources: 
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:  10.0.0.0/16
      Tags: 
        - Key: Environment
          Value: !Ref Environment
